### ISSUE TITLE
Testing ApplicationController private methods

### ISSUE THREAD

**Issue by frodsan** [lshimokawa/openspace#3]
Funciona con `send`, pero creo que es una mala práctica porque es sólo un
helper. Talvez probarlo indirectamente como un helper en la vista.

```
require 'spec_helper'

describe ApplicationController do

  it "should return current user in session" do
    user = Factory.create(:user)
    session[:user_id] = user.id
    controller.send(:current_user).should == user
  end

  it "should return current event in session" do 
    event = Factory.create(:event)
    session[:event_id] = event.id
    controller.send(:current_event).should == event
  end

end
```

**Comment by frodsan** [comment]
Help? @xenda @florent2 @goddamnhippie

**Comment by xenda** [comment]
Este tipo de cosas me gusta probarlas más como aceptación via Capybara. La prueba funciona, pero no probamos que realmente haga algo :P

**Comment by beathyate** [comment]
+1

## 

Gustavo Beathyate

**Comment by frodsan** [comment]
Closing here. I hate @frodsan and his testing paranoia.

**Comment by xenda** [comment]
He's cool.

**Comment by Florent2** [comment]
Ups sorry somehow I missed your initial help request...

Like Gustavo I'd rather use an integration test, I almost never do controller tests.

**Comment by frodsan** [comment]
For a rails app, I prefer to setup my tests like this:

```
javascripts/  # Too complex right now.
acceptance/ # The vast majority are for user interaction. I split the test by user roles if i need it.
integration/   # API Testing (controllers, message formats, headers, etc)
unit/             # Almost empty. 
```

I'm not a testing guru, but it works for me. gems/tools/etc? ... that's another story.

**Comment by Florent2** [comment]
Hum we use different terminology, by integration tests I meant what you mean by acceptance tests :)

Anyway I find that none or few unit tests might be suitable for application small and/or without much business logic, but for other kind of applications I cover the most important use cases in acceptance tests and I find that unit tests are very suitable for less important features as they run more quickly and are easier to write.

I know almost nothing about JavaScript tests, what is complex about them in the context of a Rails application?

**Comment by xenda** [comment]
@Florent2 I used to call Acceptance tests "Integration tests" as well, but since a while I've been phasing out that term after watching some really nice talks and reading some books. An integration tests is even "unit testing" logging a user if we call the data from the DB since there would be now two system we'd be integrating :). It's a little nitpick, but I think on the long term it could be clearer in talking with other devs.

I usually work tests almost the same as @frodsan. I use Acceptance tests for each feature that handles user stories, and where I've described with our clients the acceptance cases and Unit tests for dealing with logic that seems a bit harder to grasp at first look (like business domain logic, processes, aggregations, etc). Most of the other stuff usually doesn't botter me not being tested since most important bugs are caught on the Acceptance layer.

My POV is that if a bug hasn't breaks an acceptance tests, assuming they cover the right cases, it usually means is a lower priority bug, or even it's some code that never gets run (excepting from the tests :P).

Javascript testing is also my biggest pet peeve in the whole testing area :(

**Comment by frodsan** [comment]
Well, I know that you can do some UI testing with capybara, but what happens when you move your business logic to the client? How do you test JavaScript code with Ruby? Rails doesnt provide an "opinion" about that. There are a lot of options that you can use also. I made my own tool for that, i hope to get some time in the future to improve it (adding fixtures support, nice integration with rails tests, formatting, no browser). 

Again, there are a lot of options, but Rails doesnt have a default and this is kind of a problem 'cause ... It's like when you try to learn Rails and you see a lot of people saying "hey man use rspec and this ... Fuck with A, replace it with B 'cause B the new thing and blah blah". I know that people have preferences, but in most cases is like breaking one of the Rails majors goal: Avoid trivial decisions. And here we go, making apps that are harder to transfer to others. And yeah, this is the current state with JavaScript testing in Rails #ohlala.

I really like most of the Rails defaults (1. obviously i use another gems too, 2. I dont like coffee) and i hope that people could have more time to learn them well before move to something else. Its kind of sad to not have a default for testing. IMHO, I dont see too much interest in the topic.

**Comment by frodsan** [comment]
@Florent2 I dont like most of the test terminology. Basically, for a regular Rails app, I dont make "integrations tests". But we're building a couple of clients, so I like to test the API behaviour.

**Comment by Florent2** [comment]
Gracias Alvaro y Frodsan!

@frodsan

Thanks for clarifying what you mean by javascript tests being complex in the contest of a Rails application! I had not realized this before, but indeed that would definitively help if Rails had a default good choice for javascript testing (at least that would help me :) ), but can Rails pick up a default javascript test framework (or create one)? It looks like the state of the art in this domain is moving quite fast and is not really stabilized. Maybe we need some times before a JavaScript test framework emerges as the "main" one in the whole JavaScript ecosystem, and then Rails might pick this one? That's pure speculation of mine, I know too little about this :)

Very good point saying that not using the Rails defaults hurts "app transferability", it's true but I don't think that is so bad, many times it has also its advantages. Sometimes it's really better not to use the Rails default (like using jQuery when prototype was the default), sometimes the specifics of an app are better served by something different than the default (a nosql DB rather than AR), sometimes choosing the main alternative guarantees more "app transferability" as the main alternative is more used in the Rails community than the default (RSpec rather than test unit). After all one of the main goals of Rails 3 was to facilitate the use of non default options.

Looking forward to your Rails js test tool!
